
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    validation:
       cache: validator.mapping.cache.apc
    serializer:
       cache: serializer.mapping.cache.apc

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        scoreService: "@tds_marathon.scoring"
        saisonService: "@tds_marathon.saison"
        hotfreshService: "@tds_marathon.hotfresh"
    

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    variables:
        env:      [dev, prod]
        bundles: [ "FOSCommentBundle" ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8


        
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        # metadata_cache_driver: apc
        # query_cache_driver: apc
        # result_cache_driver: apc

# Swiftmailer Configuration
swiftmailer:    
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    

fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    TdS\UserBundle\Entity\User
    from_email: 
        address:    lemarathondelasemaine@gmail.com
        sender_name: le marathon de la semaine 
    registration:
        form:
            type: app_user_registration
    # change_password:
    #     form:
    #         type: me_user_change_password
    service:
            mailer: fos_user.mailer.twig_swift
    # resetting:
    #     email:
    #         template: Email/password_resetting.email.twig
    #     token_ttl: 43200



fos_comment:
    db_driver: orm
    class:
        model:
            comment: TdS\CommentBundle\Entity\Comment
            thread: TdS\CommentBundle\Entity\Thread

# web_profiler:
#     intercept_redirects: false

liip_imagine:
    default_image: ../uploads/img/anonymous.jpg
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        tiny_thumb:
            quality: 75
            filters:
                thumbnail: { size: [50, 50], mode: outbound }

        becky_thumb:
            quality: 75
            filters:
                crop: { size: [140, 140], start: [ 0,0 ] }
                thumbnail: { size: [80, 80] }

        small_thumb:
            quality: 75
            filters:
                thumbnail: { size: [100, 100], mode: outbound }

        medium_thumb:
            quality: 75
            filters:
                thumbnail: { size: [300, 300], mode: outbound }


        big_image:
            quality: 75
            filters:
                upscale: { min: [700, 700] }
                thumbnail: { size: [700, 700], mode: outbound }

        header_image:
            quality: 100
            filters:
                upscale: { min: [1920, 620] }
                

