# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

# services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    app.twig.app_extension:
        public:    false
        class:     AppBundle\Twig\AppExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    tds.cacheimage_listener:
        class: TdS\CoreBundle\Listener\CacheImageListener
        arguments: ["@liip_imagine.cache.manager"]
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemoveUpdate }

    fos_user.doctrine_registry:
        alias: doctrine

    td_s_marathon.security_type_extension:
        class: TdS\MarathonBundle\Form\Extension\SecurityTypeExtension
        arguments:
            - @security.context
        tags:
            - { name: form.type_extension, alias: form }
        
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    td_s_marathon.ckeditor:
        class: TdS\MarathonBundle\Form\Type\CkeditorType
        tags:
            - { name: form.type, alias: ckeditor }

    td_s_marathon.datepicker:
        class: TdS\MarathonBundle\Form\Type\DatepickerType
        tags:
            - { name: form.type, alias: datepicker }








