<?php

namespace TdS\MarathonBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository{
	public function findSeveral($count,$offset){

		$queryBuilder=$this->_em->createQueryBuilder()
			->select('a')
       		->orderBy('a.datePost', 'DESC')
       		->setFirstResult($offset)
   			->setMaxResults($count)
			->from($this->_entityName,'a');

		return $queryBuilder
     		->getQuery()
     		->getResult();

    
	}
}
