<?php

namespace TdS\MarathonBundle\Entity;

use TdS\UserBundle\Entity\User;

/**
 * JoggeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoggeurRepository extends \Doctrine\ORM\EntityRepository{
	public function findAll(){
        return $this->findBy(array(), array('pseudo' => 'ASC'));
    }

    public function findAllSortByLastLogin(){
    	$queryBuilder = $this->createQueryBuilder('c')
        	->addSelect('m')
        	->leftJoin('c.user', 'm')
        	->orderBy('m.lastLogin', 'DESC');

        return $queryBuilder
     		->getQuery()
     		->getResult();
    }
}
