<?php

namespace TdS\MarathonBundle\Entity;

use TdS\UserBundle\Entity\User;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * JoggeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoggeurRepository extends \Doctrine\ORM\EntityRepository{
	public function findAll(){
        return $this->findBy(array(), array('pseudo' => 'ASC'));
    }

    public function findAllSortByLastLogin(){
    	$queryBuilder = $this->createQueryBuilder('c')
        	->addSelect('c','m','partial mt.{id}','i')
        	->leftJoin('c.user', 'm')
            ->leftJoin('c.image', 'i')
            ->leftJoin('c.musicTitles','mt')
        	->orderBy('m.lastLogin', 'DESC');

        return $queryBuilder
     		->getQuery()
     		->getResult();
    }
}
