<?php

namespace TdS\MarathonBundle\Entity;

use TdS\MarathonBundle\Entity\Theme;
use Doctrine\ORM\EntityRepository;


/**
 * MusicTitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicTitleRepository extends \Doctrine\ORM\EntityRepository
{
	public function getDixieme(Theme $theme){
		$queryBuilder=$this->_em->createQueryBuilder()
			->select('a')
			->where('a.theme = :theme')
       			->setParameter('theme', $theme)
       		->orderBy('a.dateUpload', 'ASC')
       		->setFirstResult(9)
   			->setMaxResults(1)
			->from($this->_entityName,'a');


		return $queryBuilder
    		->getQuery()
    		->getResult();
	}

	public function getFirst(Theme $theme){
		$queryBuilder=$this->_em->createQueryBuilder()
			->select('a')
			->where('a.theme = :theme')
       		->setParameter('theme', $theme)
       		->orderBy('a.dateUpload', 'ASC')
       		->setFirstResult(0)
   			->setMaxResults(1)
			->from($this->_entityName,'a');


		return $queryBuilder
    		->getQuery()
    		->getResult();
	}


}
