<?php

namespace TdS\MarathonBundle\Entity;
use TdS\MarathonBundle\Entity\Theme;

/**
 * SaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonRepository extends \Doctrine\ORM\EntityRepository{
	public function findAll()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }

    public function findSaisonWithThemes($id){
        $results = $this
            ->createQueryBuilder('n')
            ->andwhere('n.id = :id')
            ->addselect('n','t','partial m.{id}','partial th.{id,numComments}')
            ->leftJoin('n.themes','t')
            ->leftJoin('t.musicTitles','m')
            ->leftJoin('t.thread','th')
            
            ->setParameter('id',$id)
            ->getQuery()->getOneOrNullResult();
 
        return $results;
    }



    public function findSaisonByThemes($id){

        $results = $this
            ->createQueryBuilder('n')
            ->andwhere('n.id = :id')
            ->addselect('n','t','partial m.{id}','partial th.{id,numComments}')
            ->leftJoin('n.themes','t')
            ->leftJoin('t.musicTitles','m')
            ->leftJoin('t.thread','th')
            
            ->setParameter('id',$id)
            ->getQuery()->getOneOrNullResult();
 
        return $results;
    }
}


