<?php

namespace TdS\MarathonBundle\Entity;
use TdS\MarathonBundle\Entity\Theme;

/**
 * SaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonRepository extends \Doctrine\ORM\EntityRepository{
	public function findAll()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }


    public function findSaisonByStatut($statut){
        $results = $this
            ->createQueryBuilder('n')
            ->addSelect('n','i')
            ->leftJoin('n.image','i')           
            ->orderBy('n.id', 'DESC')
            ->where('n.statut = :statut')
            ->setParameter('statut',$statut)
            ->setMaxResults(1)
            ->getQuery()->getOneOrNullResult();
        return $results;
    }



    public function findLastOne(){
        $results = $this
            ->createQueryBuilder('n')
            ->orderBy('n.id', 'DESC')
            ->andwhere('n.statut = :statut')
            ->setParameter('statut',2)
            ->setMaxResults(1)
            ->getQuery()->getOneOrNullResult();
        return $results;
    }


    public function findAllSaisonsWithThemes(){
        $results = $this
            ->createQueryBuilder('n')
            ->addselect('n','t','i','it','mt','partial th.{id,numComments}')
            ->leftJoin('n.image','i')
            ->leftJoin('n.themes','t')
            ->where('t.statut != :statut')
            ->setParameter('statut', 0)
            ->leftJoin('t.musicTitles','mt')
            ->leftJoin('t.image','it')
            ->leftJoin('t.thread','th')
            ->getQuery()->getResult();
 
        return $results;
    }

    public function findSaisonWithThemes($id){
        $results = $this
            ->createQueryBuilder('n')
            ->andwhere('n.id = :id')
            ->addselect('n','t','m','partial th.{id,numComments}','i','it')
            ->leftJoin('n.image','i')
            ->leftJoin('n.themes','t')
            ->leftJoin('t.image','it')
            ->leftJoin('t.musicTitles','m')
            ->leftJoin('t.thread','th')
            
            ->setParameter('id',$id)
            ->getQuery()->getOneOrNullResult();
 
        return $results;
    }

}


