<?php

namespace TdS\MarathonBundle\Entity;

/**
 * SaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonRepository extends \Doctrine\ORM\EntityRepository{
	public function findAll()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }

    // public function findLastOne(){
    // 	return $this->findBy(array('activate' => 1));
    // }

    public function findLastOne(){
    	// return $this->findBy(array(), array('id' => 'DESC'));
    	$queryBuilder=$this->_em->createQueryBuilder()
			->select('a')
       		->orderBy('a.id', 'DESC')
       		->setFirstResult(0)
   			->setMaxResults(1)
			->from($this->_entityName,'a');


		return $queryBuilder
    		->getQuery()
    		->getResult();
    }
}
