<?php
namespace TdS\MarathonBundle\Entity;
use TdS\MarathonBundle\Entity\Saison;


/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends \Doctrine\ORM\EntityRepository{
	public function findAll(){
        return $this->findBy(array(), array('dateFin' => 'DESC'));
    }

    public function findThemesBySaison(Saison $saison){
        	$queryBuilder=$this->_em->createQueryBuilder()
			->select('a')
			->where('a.saison = :saison')
       			->setParameter('saison', $saison)
       		->orderBy('a.dateDebut', 'ASC')
			->from($this->_entityName,'a');


		return $queryBuilder
    		->getQuery()
    		->getResult();
    }

    public function findOneThemeById($id){
      $queryBuilder=$this->_em->createQueryBuilder('a')
        ->addselect('a','i','j','ji','jc','jci','m','mj','th')
        ->andwhere('a.id = :id')

        ->setParameter('id', $id)
        ->from($this->_entityName,'a')
        ->leftJoin('a.image','i')
        ->leftJoin('a.joggeur','j')
        ->leftJoin('j.image','ji')
        ->leftJoin('a.joggeurChronique','jc')
        ->leftJoin('jc.image','jci')         
        ->leftJoin('a.musicTitles','m')
        ->leftJoin('m.joggeur','mj')
        ->leftJoin('a.thread','th')        
        ;

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }


    public function findOneThemeByStatut($statut){
      $queryBuilder=$this->_em->createQueryBuilder('a')
        ->addselect('a','i','j','ji','jc','jci','m','mj','th')
        ->andwhere('a.statut = :statut')

        ->setParameter('statut', $statut)
        ->from($this->_entityName,'a')
        ->leftJoin('a.image','i')
        ->leftJoin('a.joggeur','j')
        ->leftJoin('j.image','ji')
        ->leftJoin('a.joggeurChronique','jc')
        ->leftJoin('jc.image','jci')         
        ->leftJoin('a.musicTitles','m')
        ->leftJoin('m.joggeur','mj')
        ->leftJoin('a.thread','th')        
        ;

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }

    public function find3Themes(){
        $statuts=array('0','1','2');

        $queryBuilder=$this->_em->createQueryBuilder('a')
          ->addselect('a','i')
          ->andWhere('a.statut IN (:statuts)')
          ->setParameter('statuts', $statuts) 
          ->from($this->_entityName,'a')
          ->leftJoin('a.image','i')                  
          ;

          return $queryBuilder
            ->getQuery()
            ->getResult();
    }

    
}
